// <auto-generated />
namespace BeerTap.DataPersistance.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MoveKegStateFromKegsTableToTapsTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MoveKegStateFromKegsTableToTapsTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201603102240499_MoveKegStateFromKegsTableToTapsTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
